//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteApplication.AdminAuthServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorModel", Namespace="http://schemas.datacontract.org/2004/07/TranslationWebServices")]
    [System.SerializableAttribute()]
    public partial class OperatorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatorId {
            get {
                return this.OperatorIdField;
            }
            set {
                if ((this.OperatorIdField.Equals(value) != true)) {
                    this.OperatorIdField = value;
                    this.RaisePropertyChanged("OperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminAuthServiceReference.IAdminAuthService")]
    public interface IAdminAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAuthService/RegisterOperator", ReplyAction="http://tempuri.org/IAdminAuthService/RegisterOperatorResponse")]
        bool RegisterOperator(WebSiteApplication.AdminAuthServiceReference.OperatorModel userOperatorModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAuthService/RegisterOperator", ReplyAction="http://tempuri.org/IAdminAuthService/RegisterOperatorResponse")]
        System.Threading.Tasks.Task<bool> RegisterOperatorAsync(WebSiteApplication.AdminAuthServiceReference.OperatorModel userOperatorModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAuthService/AuthenticateOperator", ReplyAction="http://tempuri.org/IAdminAuthService/AuthenticateOperatorResponse")]
        bool AuthenticateOperator(WebSiteApplication.AdminAuthServiceReference.OperatorModel userOperatorModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAuthService/AuthenticateOperator", ReplyAction="http://tempuri.org/IAdminAuthService/AuthenticateOperatorResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateOperatorAsync(WebSiteApplication.AdminAuthServiceReference.OperatorModel userOperatorModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminAuthServiceChannel : WebSiteApplication.AdminAuthServiceReference.IAdminAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminAuthServiceClient : System.ServiceModel.ClientBase<WebSiteApplication.AdminAuthServiceReference.IAdminAuthService>, WebSiteApplication.AdminAuthServiceReference.IAdminAuthService {
        
        public AdminAuthServiceClient() {
        }
        
        public AdminAuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminAuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterOperator(WebSiteApplication.AdminAuthServiceReference.OperatorModel userOperatorModel) {
            return base.Channel.RegisterOperator(userOperatorModel);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterOperatorAsync(WebSiteApplication.AdminAuthServiceReference.OperatorModel userOperatorModel) {
            return base.Channel.RegisterOperatorAsync(userOperatorModel);
        }
        
        public bool AuthenticateOperator(WebSiteApplication.AdminAuthServiceReference.OperatorModel userOperatorModel) {
            return base.Channel.AuthenticateOperator(userOperatorModel);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateOperatorAsync(WebSiteApplication.AdminAuthServiceReference.OperatorModel userOperatorModel) {
            return base.Channel.AuthenticateOperatorAsync(userOperatorModel);
        }
    }
}
